name: Publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Install KCL CLI
        run: go install kcl-lang.io/cli/cmd/kcl@latest
      - name: Login to ghcr.io
        run: kcl registry login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./crossplane-provider-aws-s3
      - name: Publish to ghcr.io
        run: kcl mod push oci://ghcr.io/nicpym/kcl-modules
        working-directory: ./crossplane-provider-aws-s3
