name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        module:
          - crossplane-provider-aws-ec2
          - crossplane-provider-aws-ecr
          - crossplane-provider-aws-iam
          - crossplane-provider-aws-kms
          - crossplane-provider-aws-opensearch
          - crossplane-provider-aws-rds
          - crossplane-provider-aws-s3
          - crossplane-provider-aws-secretsmanager
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Install KCL CLI
        run: go install kcl-lang.io/cli/cmd/kcl@latest
      - name: Login to ghcr.io
        run: kcl registry login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./${{ matrix.module }}
      - name: Publish to ghcr.io
        run: kcl mod push oci://ghcr.io/nicpym/kcl-modules/${{ matrix.module }}
        working-directory: ./${{ matrix.module }}
